### ISSUE TITLE
Mostrar mais de 1 recomendação

### ISSUE THREAD

**Issue by jpsmedeiros** [jpsmedeiros/machine-learning#1]
Atualmente o método dos K vizinhos está mostrando apenas 1 recomendação, precisamos mostrar 5. 

ex:
print(knn.predict([[10, 1, 1, 0, 5, 0, 1, 2, 1, 0, 3, 2, 1, 0, 0, 22]]))

**Comment by gustavopergola** [comment]
Essa issue é útil, mas não é prioridade ao meu ver.
Como ela fala no documento, precisamos de no máximo 5 recomendações, não no mínimo.

![screenshot from 2018-06-27 19-00-00](https://user-images.githubusercontent.com/12284272/42002117-891a8284-7a3c-11e8-93b0-1f931328e31b.png)
